#!/usr/bin/env python3

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from audit_harness import audit_target, render_report


def assert_true(condition: bool, message: str) -> None:
  if not condition:
    raise AssertionError(message)


def main() -> int:
  with tempfile.TemporaryDirectory(prefix="meta-harness-audit-") as tmp:
    root = Path(tmp)
    (root / ".agents" / "skills" / "harness").mkdir(parents=True)
    (root / ".agents" / "skills" / "harness" / "SKILL.md").write_text(
      "---\nname: harness\ndescription: test\n---\n", encoding="utf-8"
    )
    (root / ".cursor" / "agents").mkdir(parents=True)
    (root / ".cursor" / "agents" / "reviewer.md").write_text("role", encoding="utf-8")
    assert_true(
      audit_target(root).existing_profiles == (".cursor/agents/reviewer.md",),
      "native profile inventory missing",
    )
    (root / ".forge" / "skills" / "harness").mkdir(parents=True)
    (root / ".codex" / "skills" / "harness").mkdir(parents=True)
    report = audit_target(root)
    assert_true(".agents/skills/harness" in report.existing_skills, "skill inventory missing")
    assert_true(any(item.name == "cursor" for item in report.detected_runtimes), "runtime missing")
    assert_true(".forge" in report.stale_artifacts, "legacy artifact missing")
    assert_true(".codex/skills/harness" in report.stale_artifacts, "Codex mirror missing")
    assert_true(report.operation_classification == "drift repair", "classification missing")
    assert_true("selected_action" not in render_report(report), "audit unexpectedly mutated")
    parsed = json.loads(render_report(report, "json"))
    assert_true(parsed["existing_roles"] == [], "unexpected role inventory")
    assert_true(parsed["existing_profiles"] == [".cursor/agents/reviewer.md"], "profile inventory missing")

  with tempfile.TemporaryDirectory(prefix="meta-harness-stale-profile-") as stale_tmp:
    stale_root = Path(stale_tmp)
    stale_profile = stale_root / ".cursor/agents/old.md"
    stale_profile.parent.mkdir(parents=True)
    stale_profile.write_text(
      "<!-- Generated by Meta Harness; edit the portable role contract instead. -->\n",
      encoding="utf-8",
    )
    stale_report = audit_target(stale_root)
    assert_true(stale_report.stale_profiles == (".cursor/agents/old.md",), "stale profile missing")
    assert_true(stale_report.operation_classification == "drift repair", "stale profile classification missing")
  print("OK: Harness audit smoke tests passed.")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
